<%@include file="Header.jsp" %>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head><b> A HERITAGE MASTERPIECE FROM LONGINES WINS A GPHG HONOUR</b>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title></title>
</head>
<body>
<br>
<img src="resources/image/wrist.jpg" alt= width="500" height="500">
 
<p>VINTAGE INSPIRED TIMEPIECES HAVE SUDDENLY BECOME THE HOTTEST PROPERTIES IN THE SWISS
  LUXURY WATCH INDUSTRY. ALMOST EVERYONE IS LOOKING FOR HERITAGE PIECES, PARTLY BECAUSE THE
  VALUATION OF THE SAME KEEPS INCREASING YEAR ON YEAR. NOT ONLY ARE THESE WATCHES AESTHETICALLY PLEASING,THEY ALSO MANAGE TO INTEGRATE SOME OF THE FINEST AND MOST TECHNOLOGICALLY ADVANCED MOVEMENTS IN THE WATCHMAKING WORLD.
  THE LONGINES AVIGATION BIGEYE’S RECENT EXPLOITS AT THE PRESTIGIOUS GPHG IS A CASE IN POINT. AT THE RECENTLY CONCLUDED 2017 EVENT, IT WALKED AWAY WITH TOP HONOURS WITH A WIN THE ‘BEST PRICE REVIVAL’ CATEGORY.
  FOR PEOPLE WHO ARE NOT FAMILIAR WITH THE SEGMENT’S TERMINOLOGY, IT SIMPLY MEANS, THAT THE AVIGATION BIGEYE WAS AWARDED THE AWARD FOR THE MOST STUNNING REISSUE OR REINTERPRETATION (WHICHEVER YOU WANT TO CALL IT) OF AN ICONIC CLASSIC WATCH. 
  </p>
  <p>THE AVIGATION BIGEYE IS AN ODE TO LONGINES’ FAMOUS WATCHMAKING TRADITIONS, AND DATES BACK TO A TIMEPIECE 
  MODEL THAT THE COMPANY MADE IN THE 1930S (MORE THAN 80 YEARS OLD!). THE THREE CHRONOMETER DASHES ON THE DIAL, 
  A CLASSIC 41 MM DIAL, CAREFULLY LAID BEZEL AND VINTAGE PUSHERS, ALONG WITH THE USE OF SUPER LUMINOVA ON THE ARABIC NUMERALS MANAGES 
  TO CONVERT THE AVIGATION BIGEYE INTO A HARD-CORE PILOT WATCH, BOTH IN TERMS OF ITS VISUAL ASPECT, 
  AS WELL AS THE QUALITY OF THE MOVEMENT POWERING THE TIMEPIECE. 
  
</p>
 
 
</body>
</html>